// /secure/login.c - Login handler for Dawn of the Dragons
// Replica of discworld.starturtle.net:4242, Rethemed to Forgotten Realms
// March 4, 2025, Generated by Grok 3

#include <config.h>
#include "/include/master.h"

#define START_ROOM "/dawn/lib/core/starting_room"

nosave string name;
nosave string race;
nosave int step;

void create() {
    write("Welcome to Dawn of the Dragons!\n");
    write("A realm of Faerûn, forged in the fires of Forgotten Realms.\n");
    write("Enter your name, adventurer: ");
    step = 1;
    input_to("handle_input");
}

void handle_input(string str) {
    object player;
    string *races = ({ "human", "elf", "dwarf", "halfling", "gnome" });
    
    switch (step) {
        case 1: // Name entry
            if (!str || str == "") {
                write("A name is required, traveler. Try again: ");
                input_to("handle_input");
                return;
            }
            name = lower_case(str);
            if (file_size("/dawn/lib/players/" + name[0..0] + "/" + name + ".o") > 0) {
                write("That name is claimed by another soul. Choose another: ");
                input_to("handle_input");
                return;
            }
            write("Well met, " + capitalize(name) + "!\n");
            write("Choose your race (" + implode(races, ", ") + "): ");
            step = 2;
            input_to("handle_input");
            break;
            
        case 2: // Race choice
            if (member_array(lower_case(str), races) == -1) {
                write("Unknown race. Options: " + implode(races, ", ") + "\nTry again: ");
                input_to("handle_input");
                return;
            }
            race = lower_case(str);
            player = clone_object("/dawn/lib/core/player");
            if (!player) {
                write("Error: The weave fails—cannot forge your essence.\n");
                destruct(this_object());
                return;
            }
            player->set_player_name(name);
            player->set_race(race);
            if (!find_object(START_ROOM)) {
                if (catch(load_object(START_ROOM))) {
                    write("Error: The portals to " + START_ROOM + " are sealed.\n");
                    destruct(player);
                    destruct(this_object());
                    return;
                }
            }
            if (player->move(START_ROOM)) {
                write("Error: Cannot transport you to " + START_ROOM + ".\n");
                destruct(player);
                destruct(this_object());
                return;
            }
            write("You materialize in " + START_ROOM->query_short() + ".\n");
            write("Use 'look' to survey, 'go <direction>' to travel.\n");
            exec(player, this_object());
            destruct(this_object());
            break;
    }
}
