// Master header for Dawn of the Dragons
// Generated by Grok 3, March 4, 2025

#ifndef __MASTER_H
#define __MASTER_H

#define MASTER "/secure/master"
#define SIMUL_EFUN "/secure/simul_efun"
#define LOG_DIR "/log" // Relative to mudlib directory
#define START_ROOM "/room/void"

// Function prototypes
string creator_file(string fname);
string domain_file(string fname);
object connect();
void log_error(string file, string err);
string valid_read(string path, object caller);
string valid_write(string path, object caller);
int valid_object(object ob);
void preload(string file);
int query_port();
void external_start(int cmd, string args, string read_func, string write_func, string close_func);

#endif
