// Generated by Tyr (Greater Deity) on 2025-03-01 06:55:56 - Justice domain

#ifndef LOGIN_H
#define LOGIN_H
typedef struct {
    char* name;
    char* password;
    char* gender;
    int mxp;
    int mccp;
    int term;
} player_t;
void handle_login(player_t* player);
void create_player_file(player_t* player, const char* format, const char* name);
void enable_mxp(player_t* player);
void enable_mccp(player_t* player);
#endif
