// Generated by Tyr (Greater Deity) on 2025-03-01 06:55:56 - Justice domain

#include "login.h"
#include <string.h>
void handle_login(player_t* player) {
    printf("Welcome to Archaon MUD, %s! (MCCP/MXP enabled)\n", player->name);
    // FluffOS driver integration
    if (player->mxp) enable_mxp(player);
    if (player->mccp) enable_mccp(player);
    // Basic character creation
    create_player_file(player, "%s.plr", player->name);
}
void create_player_file(player_t* player, const char* format, const char* name) {
    char path[256];
    snprintf(path, sizeof(path), format, name);
    FILE* fp = fopen(path, "w");
    if (fp) {
        fprintf(fp, "name: %s\npassword: %s\ngender: %s\nrace: human\n", name, player->password, player->gender);
        fclose(fp);
    }
}
