// /dawn/lib/core/player.c - Player object for Dawn of the Dragons
// Replica of discworld.starturtle.net:4242, Rethemed to Forgotten Realms
// March 4, 2025, Generated by Grok 3

#include <config.h>
#include "/include/master.h"

inherit "/dawn/lib/core/object";

nosave string player_name;
nosave string race;
nosave mapping stats = ([ "strength": 10, "dexterity": 10, "constitution": 10, 
                          "intelligence": 10, "wisdom": 10, "charisma": 10 ]);
nosave mapping skills = ([ "sword": 0, "stealth": 0, "arcana": 0 ]);
nosave int xp;
nosave int gold;
nosave int last_login;

void create() {
    ::create();
    set_name("wanderer");
    player_name = "wanderer";
    race = "human";
    xp = 0;
    gold = 0;
    last_login = time();
    add_action("do_move", "go");
    add_action("do_look", "look");
    add_action("do_say", "say");
}

void setup() {
    set_short(capitalize(player_name) + " the " + race);
    set_long(capitalize(player_name) + ", a " + race + " adventurer from Faerûn.\n");
    set_gender("unknown");
}

void set_player_name(string str) {
    player_name = str;
    set_name(str);
    set_short(capitalize(str) + " the " + race);
}

void set_race(string r) {
    race = r;
    set_short(capitalize(player_name) + " the " + race);
}

string query_race() { return race; }
string query_player_name() { return player_name; }
int query_xp() { return xp; }
void add_xp(int amount) { xp += amount; }
int query_gold() { return gold; }
void add_gold(int amount) { gold += amount; }
int query_last_login() { return last_login; }

void adjust_stat(string stat, int value) {
    if (stats[stat]) stats[stat] += value;
}

int query_stat(string stat) {
    return stats[stat] ? stats[stat] : 0;
}

void adjust_skill(string skill, int value) {
    if (!skills) skills = ([ ]);
    skills[skill] += value;
}

int query_skill(string skill) {
    return skills[skill] ? skills[skill] : 0;
}

int do_move(string dir) {
    object env = environment(this_object());
    string dest;
    if (!env) {
        write("You drift in the Ethereal Plane—something’s amiss!\n");
        return 1;
    }
    dest = env->query_exit(dir);
    if (!dest) {
        write("No path leads " + dir + " from here.\n");
        return 1;
    }
    if (!move(dest)) {
        write("You traverse " + dir + " to " + load_object(dest)->query_short() + ".\n");
        say(player_name + " strides " + dir + ".\n");
        command("look");
        return 1;
    }
    write("The way " + dir + " is barred.\n");
    return 1;
}

int do_look(string str) {
    object env = environment(this_object());
    if (!env) {
        write("A void surrounds you—nothing to behold.\n");
        return 1;
    }
    write(env->long() + "\n");
    foreach (object ob in all_inventory(env)) {
        if (ob != this_object()) {
            write(ob->short() + " stands here.\n");
        }
    }
    write("Paths lead: " + implode(keys(env->query_exits()), ", ") + "\n");
    return 1;
}

int do_say(string str) {
    if (!str) {
        write("Speak what words?\n");
        return 1;
    }
    write("You say: " + str + "\n");
    say(player_name + " says: " + str + "\n");
    return 1;
}
