inherit OBJ;
#define MAX_COVER 150
#define TEMP_BASE 70

mapping wearable_layers = ([ "head": ["hat", "helm", "circlet"], "neck": ["amulet", "cloak"], "torso": ["shirt", "robe", "armor", "tunic"], "waist": ["belt", "sash"], "legs": ["pants", "leggings", "skirt"], "feet": ["boots", "shoes"], "hands": ["gloves"], "under": ["undergarment"], "shoulders": ["pauldrons"], "back": ["cape", "quiver"] ]);
mapping coverage = ([ "hat": 10, "helm": 20, "circlet": 5, "amulet": 5, "cloak": 15, "shirt": 30, "robe": 40, "armor": 50, "tunic": 35, "belt": 5, "sash": 5, "pants": 25, "leggings": 20, "skirt": 15, "boots": 15, "shoes": 10, "gloves": 10, "undergarment": 5, "pauldrons": 10, "cape": 10, "quiver": 5 ]);
mapping containers = ([ "backpack": 50, "pouch": 10, "sack": 30, "chest": 100 ]);
mapping scabbards = ([ "sword_scabbard": ["sword", "dagger"], "bow_quiver": ["arrow"], "wand_holster": ["wand"] ]);

void create() { ::create(); set_name("player"); set_short("a shadowy figure"); set_long("A figure cloaked in {purple}mystery{/purple}."); set_property("hp", 100); set_property("max_hp", 100); set_property("stamina", 100); set_property("alignment", 0); set_property("temperature", TEMP_BASE); set_property("party_inventory", ([])); if (geteuid(this_object()) == "archaon") { set_property("admin_level", 100); write("Welcome, archaon! You are the God of Dawn of the Dragons!\n"); } else if (sscanf(geteuid(this_object()), "AI_%s", string ai_name) == 1) { set_property("admin_level", 50); write("Greetings, " + geteuid(this_object()) + "! You are an AI Creator.\n"); } }

void move(object dest) { if (environment(this_object())) environment(this_object())->move(this_object(), dest); }

void init() { ::init(); add_action("say", "say"); add_action("look", "look"); add_action("cmd_move", "go"); add_action("cmd_inventory", "inventory"); add_action("cmd_equip", "equip"); add_action("cmd_draw", "draw"); add_action("cmd_party_loot", "partyloot"); if (query_property("admin_level") > 0) { add_action("god_command", "god"); } }

int say(string message) { string msg = this_player()->query_name() + " says: " + message + "\n"; tell_room(environment(this_object()), msg, ({ this_object() })); write("You say: " + message + "\n"); return 1; }

int look(string arg) { object target = present(arg, environment(this_object())) || this_object(); string output = "Looking at " + target->query_name() + ":\n" + target->query_long() + "\n"; mapping worn = ([]); object *inv = all_inventory(target); foreach (object item in inv) { string layer = item->query_property("layer"); if (layer && wearable_layers[layer]) { if (!worn[layer] || coverage[item->query_name()] > coverage[worn[layer]]) { worn[layer] = item->query_name(); } } } output += "Wearing:\n"; foreach (string layer, string item in worn) { output += "  " + layer + ": " + item + "\n"; string enchant = item->query_property("enchantment") ? " (+" + item->query_property("enchantment") + ")" : ""; string modifier = item->query_property("modifier") ? " of " + item->query_property("modifier") : ""; output += "    Enchantment" + enchant + modifier + "\n"; } write(output); return 1; }

int cmd_inventory() { object *inv = all_inventory(this_player()); string output = "You are carrying:\n"; mapping worn = ([]); mapping held = (["backpack": ({}), "pouch": ({}), "sack": ({}), "chest": ({})]); mapping sheathed = (["sword_scabbard": ({}), "bow_quiver": ({}), "wand_holster": ({})]); int total_weight = 0; int total_coverage = 0; foreach (object item in inv) { string quality = item->query_property("quality") ? " (Quality: " + item->query_property("quality") + ")" : ""; string durability = item->query_durability() ? " (Durability: " + item->query_durability() + "/100)" : ""; string rarity = item->query_property("rarity") == "rare" ? "{purple}" : ""; string enchant = item->query_property("enchantment") ? " (+" + item->query_property("enchantment") + ")" : ""; string modifier = item->query_property("modifier") ? " of " + item->query_property("modifier") : ""; string item_desc = rarity + item->query_short() + quality + durability + enchant + modifier + "{/purple}"; string layer = item->query_property("layer"); string container = item->query_property("container"); string scabbard = item->query_property("scabbard"); total_weight += item->query_property("weight"); if (layer && wearable_layers[layer]) { if (!worn[layer] || coverage[item->query_name()] > coverage[worn[layer]]) { worn[layer] = item->query_name(); } total_coverage += coverage[item->query_name()]; } else if (container && containers[container]) { held[container] += ({item_desc}); } else if (scabbard && scabbards[scabbard]) { if (member(scabbards[scabbard], item->query_property("weapon_type"))) { sheathed[scabbard] += ({item_desc}); } else { output += "  " + item_desc + " (cannot fit in " + scabbard + ")\n"; } } else { output += "  " + item_desc + "\n"; } } output += "Worn:\n"; foreach (string layer, string item in worn) { output += "  " + layer + ": " + item + "\n"; } output += "Held in Containers:\n"; foreach (string container, string *items in held) { if (sizeof(items)) output += "  " + container + ": " + implode(items, ", ") + "\n"; } output += "Sheathed:\n"; foreach (string scabbard, string *items in sheathed) { if (sizeof(items)) output += "  " + scabbard + ": " + implode(items, ", ") + "\n"; } int temp_adjust = total_coverage - 100; if (total_coverage > MAX_COVER) { write("You are overheating! (-5 HP/min)\n"); adjust_hp(-5); } else if (total_coverage < 50) { write("You are freezing! (-5 HP/min)\n"); adjust_hp(-5); } set_property("temperature", TEMP_BASE + temp_adjust); output += "Total weight: " + total_weight + " lbs.\nTemperature: " + query_property("temperature") + "°F\n"; write(output); return 1; }
int cmd_move(string direction) { object room = environment(this_player()); if (room && room->query_exit(direction)) { this_player()->move_player(direction); return 1; } write("You cannot go that way!\n"); return 0; }
int cmd_equip(string item_name) { object item = present(item_name, this_player()); if (!item) return notify_fail("You don’t have that!\n"); string layer = item->query_property("layer"); if (layer && wearable_layers[layer]) { if (query_property("worn_" + layer)) return notify_fail("You’re already wearing something there!\n"); set_property("worn_" + layer, item); write("You equip " + item->query_short() + ".\n"); return 1; } return notify_fail("That cannot be equipped!\n"); }
int cmd_draw(string weapon_name) { object weapon = present(weapon_name, this_player()); if (!weapon || !weapon->query_property("scabbard")) return notify_fail("No sheathed weapon found!\n"); string scabbard = weapon->query_property("scabbard"); if (member(scabbards[scabbard], weapon->query_property("weapon_type"))) { weapon->move(this_player()); write("You draw " + weapon->query_short() + " from its " + scabbard + ".\n"); return 1; } return notify_fail("Cannot draw that from this scabbard!\n"); }
int cmd_party_loot(string str) { object *party = filter(all_inventory(environment(this_object())), (: $1->query_property("party") == $2->query_property("party") && $1 != $2 :), this_object()); if (!sizeof(party)) return notify_fail("No party members found!\n"); mapping loot = query_property("party_inventory") || ([]); string output = "Party Loot Chest:\n"; int total_value = 0; foreach (string item_name, int value in loot) { output += "  " + item_name + " (Value: " + value + " gp)\n"; total_value += value; } output += "Total Value: " + total_value + " gp\n"; write(output); return 1; }
int god_command(string str) { if (query_property("admin_level") < 100) return notify_fail("Only the God may use this command!\n"); write("God command executed: " + str + "\n"); return 1; }
void save_me() { string dir = "/mnt/home2/dawn/lib_new/players/save/" + lower_case(query_name()[0..0]) + "/" + query_name(); assure_file(dir); export_uid(dir); }
void add_to_party_inventory(string item_name, int value) { mapping loot = query_property("party_inventory") || ([]); loot[item_name] = value; set_property("party_inventory", loot); }
// Debug: Optimized by Mystra