// /lib/core/player.c - Merged Player Object for Dawn of the Dragons
// Replica of discworld.starturtle.net:4242, Rethemed to Forgotten Realms
// March 4, 2025, Generated by Grok 3

#include <config.h>
#include "/include/master.h"

inherit "/lib/std/object";

#define MAX_COVER 150
#define TEMP_BASE 70

nosave string player_name;
nosave string race;
nosave mappingTH stats = ([ "strength": 10, "dexterity": 10, "constitution": 10, 
 "intelligence": 10, "wisdom": 10, "charisma": 10 ]);
nosave mapping skills = ([ "sword": 0, "stealth": 0, "arcana": 0 ]);
nosave int xp;
nosave int gold;
nosave int last_login;
nosave int hp = 100;
nosave int max_hp = 100;
nosave int stamina = 100;
nosave int alignment = 0;
nosave int temperature = TEMP_BASE;
nosave mapping party_inventory = ([]);
nosave mapping wearable_layers = ([ "head": ({ "hat", "helm", "circlet" }), 
 "neck": ({ "amulet", "cloak" }), 
 "torso": ({ "shirt", "robe", "armor", "tunic" }), 
 "waist": ({ "belt", "sash" }), 
 "legs": ({ "pants", "leggings", "skirt" }), 
 "feet": ({ "boots", "shoes" }), 
 "hands": ({ "gloves" }), 
 "under": ({ "undergarment" }), 
 "shoulders": ({ "pauldrons" }), 
 "back": ({ "cape", "quiver" }) ]);
nosave mapping coverage = ([ "hat": 10, "helm": 20, "circlet": 5, "amulet": 5, "cloak": 15, 
 "shirt": 30, "robe": 40, "armor": 50, "tunic": 35, "belt": 5, 
 "sash": 5, "pants": 25, "leggings": 20, "skirt": 15, "boots": 15, 
 "shoes": 10, "gloves": 10, "undergarment": 5, "pauldrons": 10, 
 "cape": 10, "quiver": 5 ]);
nosave mapping containers = ([ "backpack": 50, "pouch": 10, "sack": 30, "chest": 100 ]);
nosave mapping scabbards = ([ "sword_scabbard": ({ "sword", "dagger" }), 
 "bow_quiver": ({ "arrow" }), 
 "wand_holster": ({ "wand" }) ]);

void create() {
 ::create();
 set_name("wanderer");
 player_name = "wanderer";
 race = "human";
 xp = 0;
 gold = 0;
 last_login = time();
 add_action("do_move", "go");
 add_action("do_look", "look");
 add_action("do_say", "say");
 add_action("do_inventory", "inventory");
 add_action("do_equip", "equip");
 add_action("do_draw", "draw");
 add_action("do_party_loot", "partyloot");
 if (geteuid(this_object()) == "archaon") {
 set_property("admin_level", 100);
 write("Welcome, archaon! You are the God of Dawn of the Dragons!\n");
 add_action("god_command", "god");
 } else if (sscanf(geteuid(this_object()), "AI_%s", string ai_name) == 1) {
 set_property("admin_level", 50);
 write("Greetings, " + geteuid(this_object()) + "! You are an AI Creator.\n");
 add_action("god_command", "god");
 }
 load_player();
}

void setup() {
 set_short(capitalize(player_name) + " the " + race);
 set_long(capitalize(player_name) + ", a " + race + " adventurer from Faerûn.\n");
 set_gender("unknown");
}

void set_player_name(string str) {
 player_name = str;
 set_name(str);
 set_short(capitalize(str) + " the " + race);
}

void set_race(string r) {
 race = r;
 set_short(capitalize(player_name) + " the " + race);
}

string query_race() { return race; }
string query_player_name() { return player_name; }
int query_xp() { return xp; }
void add_xp(int amount) { xp += amount; save_player(); }
int query_gold() { return gold; }
void add_gold(int amount) { gold += amount; save_player(); }
int query_hp() { return hp; }
void adjust_hp(int amount) { hp += amount; if (hp < 0) hp = 0; save_player(); }
int query_max_hp() { return max_hp; }
void set_max_hp(int value) { max_hp = value; save_player(); }
int query_stamina() { return stamina; }
void adjust_stamina(int amount) { stamina += amount; save_player(); }
int query_alignment() { return alignment; }
void adjust_alignment(int amount) { alignment += amount; save_player(); }
int query_temperature() { return temperature; }
int query_last_login() { return last_login; }

void adjust_stat(string stat, int value) {
 if (stats[stat]) stats[stat] += value;
 save_player();
}

int query_stat(string stat) {
 return stats[stat] ? stats[stat] : 0;
}

void adjust_skill(string skill, int value) {
 if (!skills) skills = ([ ]);
 skills[skill] += value;
 save_player();
}

int query_skill(string skill) {
 return skills[skill] ? skills[skill] : 0;
}

void save_player() {
 string path = "/lib/players/save/" + player_name[0..0] + "/" + player_name;
 if (!unguarded((: save_object, path :))) {
 write("Failed to etch your essence into the Weave.\n");
 }
}

void load_player() {
 string path = "/lib/players/save/" + player_name[0..0] + "/" + player_name;
 if (file_size(path + ".o") > 0) {
 unguarded((: restore_object, path :));
 }
}

int do_move(string dir) {
 object env = environment(this_object());
 string dest;
 if (!env) {
 write("You drift in the Ethereal Plane—something’s broken!\n");
 return 1;
 }
 dest = env->query_exit(dir);
 if (!dest) {
 write("No path leads " + dir + " from here.\n");
 return 1;
 }
 if (!move(dest)) {
 write("You traverse " + dir + " to " + load_object(dest)->query_short() + ".\n");
 say(player_name + " strides " + dir + ".\n");
 command("look");
 return 1;
 }
 write("The way " + dir + " is barred.\n");
 return 1;
}

int do_look(string str) {
 object target = str ? present(str, environment(this_object())) || present(str, this_object()) : environment(this_object());
 if (!target) {
 write("You see nothing by that name.\n");
 return 1;
 }
 string output = "Looking at " + target->query_name() + ":\n" + target->query_long() + "\n";
 mapping worn = ([]);
 object *inv = all_inventory(target);
 foreach (object item in inv) {
 string layer = item->query_property("layer");
 if (layer && wearable_layers[layer]) {
 if (!worn[layer] || coverage[item->query_name()] > coverage[worn[layer]]) {
 worn[layer] = item->query_name();
 }
 }
 }
 output += "Wearing:\n";
 foreach (string layer, string item in worn) {
 output += " " + layer + ": " + item + "\n";
 string enchant = item->query_property("enchantment") ? " (+" + item->query_property("enchantment") + ")" : "";
 string modifier = item->query_property("modifier") ? " of " + item->query_property("modifier") : "";
 output += " Enchantment" + enchant + modifier + "\n";
 }
 write(output);
 return 1;
}

int do_say(string str) {
 if (!str) {
 write("Speak what words?\n");
 return 1;
 }
 write("You say: " + str + "\n");
 say(player_name + " says: " + str + "\n");
 return 1;
}

int do_inventory() {
 object *inv = all_inventory(this_object());
 string output = "You are carrying:\n";
 mapping worn = ([]);
 mapping held = (["backpack": ({}), "pouch": ({}), "sack": ({}), "chest": ({})]);
 mapping sheathed = (["sword_scabbard": ({}), "bow_quiver": ({}), "wand_holster": ({})]);
 int total_weight = 0;
 int total_coverage = 0;
 foreach (object item in inv) {
 string quality = item->query_property("quality") ? " (Quality: " + item->query_property("quality") + ")" : "";
 string durability = item->query_durability() ? " (Durability: " + item->query_durability() + "/100)" : "";
 string rarity = item->query_property("rarity") == "rare" ? "{purple}" : "";
 string enchant = item->query_property("enchantment") ? " (+" + item->query_property("enchantment") + ")" : "";
 string modifier = item->query_property("modifier") ? " of " + item->query_property("modifier") : "";
 string item_desc = rarity + item->query_short() + quality + durability + enchant + modifier + "{/purple}";
 string layer = item->query_property("layer");
 string container = item->query_property("container");
 string scabbard = item->query_property("scabbard");
 total_weight += item->query_property("weight") || 0;
 if (layer && wearable_layers[layer]) {
 if (!worn[layer] || coverage[item->query_name()] > coverage[worn[layer]]) {
 worn[layer] = item->query_name();
 }
 total_coverage += coverage[item->query_name()];
 } else if (container && containers[container]) {
 held[container] += ({item_desc});
 } else if (scabbard && scabbards[scabbard]) {
 if (member_array(item->query_property("weapon_type"), scabbards[scabbard]) != -1) {
 sheathed[scabbard] += ({item_desc});
 } else {
 output += " " + item_desc + " (cannot fit in " + scabbard + ")\n";
 }
 } else {
 output += " " + item_desc + "\n";
 }
 }
 output += "Worn:\n";
 foreach (string layer, string item in worn) {
 output += " " + layer + ": " + item + "\n";
 }
 output += "Held in Containers:\n";
 foreach (string container, string *items in held) {
 if (sizeof(items)) output += " " + container + ": " + implode(items, ", ") + "\n";
 }
 output += "Sheathed:\n";
 foreach (string scabbard, string *items in sheathed) {
 if (sizeof(items)) output += " " + scabbard + ": " + implode(items, ", ") + "\n";
 }
 int temp_adjust = total_coverage - 100;
 if (total_coverage > MAX_COVER) {
 write("You are overheating in Faerûn’s sun! (-5 HP/min)\n");
 adjust_hp(-5);
 } else if (total_coverage < 50) {
 write("You are freezing in the North’s chill! (-5 HP/min)\n");
 adjust_hp(-5);
 }
 temperature = TEMP_BASE + temp_adjust;
 output += "Total weight: " + total_weight + " lbs.\nTemperature: " + temperature + "°F\n";
 write(output);
 return 1;
}

int do_equip(string item_name) {
 object item = present(item_name, this_object());
 if (!item) return notify_fail("You don’t have that in your possession!\n");
 string layer = item->query_property("layer");
 if (layer && wearable_layers[layer]) {
 if (query_property("worn_" + layer)) return notify_fail("You’re already clad there!\n");
 set_property("worn_" + layer, item);
 write("You equip " + item->query_short() + ".\n");
 return 1;
 }
 return notify_fail("That cannot be worn!\n");
}

int do_draw(string weapon_name) {
 object weapon = present(weapon_name, this_object());
 if (!weapon || !weapon->query_property("scabbard")) return notify_fail("No sheathed weapon found by that name!\n");
 string scabbard = weapon->query_property("scabbard");
 if (member_array(weapon->query_property("weapon_type"), scabbards[scabbard]) != -1) {
 weapon->move(this_object());
 write("You draw " + weapon->query_short() + " from its " + scabbard + ".\n");
 return 1;
 }
 return notify_fail("Cannot draw that from this scabbard!\n");
}

int do_party_loot(string str) {
 object *party = filter_array(all_inventory(environment(this_object())), 
 (: $1->query_property("party") == $2->query_property("party") && $1 != $2 :), 
 this_object());
 if (!sizeof(party)) return notify_fail("No companions share your banner!\n");
 mapping loot = query_property("party_inventory") || ([]);
 string output = "Party Trove:\n";
 int total_value = 0;
 foreach (string item_name, int value in loot) {
 output += " " + item_name + " (Value: " + value + " gp)\n";
 total_value += value;
 }
 output += "Total Value: " + total_value + " gp\n";
 write(output);
 return 1;
}

int god_command(string str) {
 int admin_level = query_property("admin_level");
 if (admin_level < 50) return notify_fail("Only Creators and Gods wield this power!\n");
 if (admin_level >= 100) {
 write("God command executed: " + str + "\n");
 } else {
 write("Creator command executed: " + str + "\n");
 }
 return 1;
}

void add_to_party_inventory(string item_name, int value) {
 mapping loot = query_property("party_inventory") || ([]);
 loot[item_name] = value;
 set_property("party_inventory", loot);
}
