// /dawn/lib/core/starting_room.c - Starting room for Dawn of the Dragons
// Rethemed to Forgotten Realms, March 4, 2025
// Generated by Grok 3

#include <config.h>
#include "/include/master.h"

inherit "/dawn/lib/core/room";

void create() {
    ::create();
    set_short("Waterdeep Market Square");
    set_long("A bustling square in Waterdeep, heart of the Sword Coast. Merchants hawk wares, adventurers barter tales, and the scent of salt and steel fills the air.\n");
    set_exits(([
        "north": "/dawn/lib/core/north_street",
        "east": "/dawn/lib/core/east_alley"
    ]));
}
